# Generated by Django 4.2.3 on 2023-07-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_remove_board_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='body',
            field=models.TextField(),
        ),
    ]
