# Generated by Django 4.2.3 on 2023-07-09 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board'),
        ),
    ]
